# Default values for mabi-ah-discord.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: dqle/mabi-ah-discord
  tag: latest
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:
  DISCORD_API_TOKEN: ""
  DISCORD_SERVER_ID: ""
  DISCORD_CHANNEL_ID: ""
  MONGODB_CONNECTION_STRING: ""